// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tunnel.proto

package tunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	"sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelData carries tunnel traffic in both directions
type TunnelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Data         []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Types that are assignable to Control:
	//	*TunnelData_Init
	//	*TunnelData_Close
	Control isTunnelData_Control `protobuf_oneof:"control"`
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelData) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (m *TunnelData) GetControl() isTunnelData_Control {
	if m != nil {
		return m.Control
	}
	return nil
}

func (x *TunnelData) GetInit() *TunnelInit {
	if x, ok := x.GetControl().(*TunnelData_Init); ok {
		return x.Init
	}
	return nil
}

func (x *TunnelData) GetClose() *TunnelClose {
	if x, ok := x.GetControl().(*TunnelData_Close); ok {
		return x.Close
	}
	return nil
}

type isTunnelData_Control interface {
	isTunnelData_Control()
}

type TunnelData_Init struct {
	Init *TunnelInit `protobuf:"bytes,10,opt,name=init,proto3,oneof"`
}

type TunnelData_Close struct {
	Close *TunnelClose `protobuf:"bytes,11,opt,name=close,proto3,oneof"`
}

func (*TunnelData_Init) isTunnelData_Control() {}

func (*TunnelData_Close) isTunnelData_Control() {}

// TunnelInit is sent as the first message to initialize the tunnel
type TunnelInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	AgentId      string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ResourceName string `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Protocol     string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *TunnelInit) Reset() {
	*x = TunnelInit{}
}

func (x *TunnelInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInit) ProtoMessage() {}

func (x *TunnelInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*TunnelInit) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelInit) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *TunnelInit) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TunnelInit) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *TunnelInit) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// TunnelClose signals tunnel termination
type TunnelClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	BytesSent     int64  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived int64  `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
}

func (x *TunnelClose) Reset() {
	*x = TunnelClose{}
}

func (x *TunnelClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClose) ProtoMessage() {}

func (x *TunnelClose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*TunnelClose) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TunnelClose) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TunnelClose) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

// HeartbeatRequest is sent periodically to maintain connection
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActiveTunnels int32  `protobuf:"varint,2,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveTunnels() int32 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

// HeartbeatResponse acknowledges the heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

var file_proto_tunnel_proto_rawDesc = []byte{
	// Placeholder - actual bytes would be generated by protoc
}

var file_proto_tunnel_proto_rawDescOnce sync.Once
var file_proto_tunnel_proto_rawDescData = file_proto_tunnel_proto_rawDesc

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		// Placeholder - would use gzip compression
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tunnel_proto_goTypes = []interface{}{
	(*TunnelData)(nil),       // 0: bamf.tunnel.v1.TunnelData
	(*TunnelInit)(nil),       // 1: bamf.tunnel.v1.TunnelInit
	(*TunnelClose)(nil),      // 2: bamf.tunnel.v1.TunnelClose
	(*HeartbeatRequest)(nil), // 3: bamf.tunnel.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: bamf.tunnel.v1.HeartbeatResponse
}
var file_proto_tunnel_proto_depIdxs = []int32{
	1, // 0: bamf.tunnel.v1.TunnelData.init:type_name -> bamf.tunnel.v1.TunnelInit
	2, // 1: bamf.tunnel.v1.TunnelData.close:type_name -> bamf.tunnel.v1.TunnelClose
	0, // 2: bamf.tunnel.v1.TunnelService.EstablishTunnel:input_type -> bamf.tunnel.v1.TunnelData
	3, // 3: bamf.tunnel.v1.TunnelService.Heartbeat:input_type -> bamf.tunnel.v1.HeartbeatRequest
	0, // 4: bamf.tunnel.v1.TunnelService.EstablishTunnel:output_type -> bamf.tunnel.v1.TunnelData
	4, // 5: bamf.tunnel.v1.TunnelService.Heartbeat:output_type -> bamf.tunnel.v1.HeartbeatResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }

func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tunnel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tunnel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_tunnel_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TunnelData_Init)(nil),
		(*TunnelData_Close)(nil),
	}
}
