{{- if and .Values.outpost.enabled .Values.outpost.proxy.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bamf.fullname" . }}-proxy
  labels:
    {{- include "bamf.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bamf.fullname" . }}-proxy
  minReplicas: {{ .Values.outpost.proxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.outpost.proxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.outpost.proxy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.outpost.proxy.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.outpost.proxy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.outpost.proxy.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
