{{- if and .Values.agent.enabled .Values.agent.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bamf.fullname" . }}-agent
  labels:
    {{- include "bamf.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  maxUnavailable: {{ .Values.agent.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "bamf.agent.selectorLabels" . | nindent 6 }}
{{- end }}
